### ISSUE TITLE
NPM install fails on "async" function

### ISSUE THREAD

**Issue by svHatch** [sebastiancarlos/beachpatrol#3]
`
user@domain:~/bin/beachpatrol$` npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@playwright/test@1.44.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'playwright@1.44.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'playwright-core@1.44.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

> beachpatrol@0.0.3 postinstall
> node ./.internal-scripts/postinstall.js

file:///home/user/bin/beachpatrol/.internal-scripts/postinstall.js:64
if ((await getInstalledBrowsers()).length === 0) {
     ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/user/bin/beachpatrol
npm ERR! command failed
npm ERR! command sh -c node ./.internal-scripts/postinstall.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2024-08-23T19_14_58_499Z-debug-0.log
`

Log file is attached.

[2024-08-23T19_14_58_499Z-debug-0.log](https://github.com/user-attachments/files/16732935/2024-08-23T19_14_58_499Z-debug-0.log)

**Comment by sebastiancarlos** [comment]
Thanks for the report! The issue is that your node version is below than required one (It should be 16 or later). I added a check for this on the project's `package.json` at 3af52067
